### ISSUE TITLE
step button (next, previous,finish) writen into div

### ISSUE THREAD

**Issue by miyan27** [mstratman/jQuery-Smart-Wizard#89] opened 2016-04-15 10:48 UTC
Hi I wanna ask about the step button (next, previous,finish).
I want it to be write inside the <div></div>
is that possible to write the step button like this bellow?
<div class="naviButtons">
                   <a href="#" class="buttonFinish button buttonDisabled">send</a>
                   <a href="#" class="buttonNext button"><a>next</a>
                  <a href="#" class="buttonPrevious button buttonDisabled">previous</a>
</div>
if yes,please tell me how,
i tried to edit the source of jquery.smartWizard 
but..it couldn't be added. 
please someone tell me how to write it inside the <div></div>

Thank you

**Comment by mstratman** [comment] 2016-05-09 16:35
Closing as duplicate of https://github.com/mstratman/jQuery-Smart-Wizard/issues/90

**Closed by mstratman** 2016-05-09 16:35 UTC
